{
 "title": "learning",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Свободное место на файловой системе",
   "type": "graph",
   "description": "Свободное место на файловой системе",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}\r"
    }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "graph",
   "description": "Свободная оперативная память",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes{}\r" }
   ]
  },
  {
   "title": "Утилизация CPU (100-idle)",
   "type": "graph",
   "description": "Утилизация CPU (100-idle)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Load Average (1/5/15)",
   "type": "graph",
   "description": "Load Average (1/5/15)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1{}" },
    { "expr": "node_load5{}" },
    { "expr": "node_load15{}" }
   ]
  }
 ]
}